
package com.msci.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.1
 * 2015-07-30T15:21:08.885+05:30
 * Generated source version: 3.1.1
 * 
 */
public final class Calculator_CalculatorPort_Client {

    private static final QName SERVICE_NAME = new QName("http://msci.com/", "CalculatorService");

    private Calculator_CalculatorPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = CalculatorService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        CalculatorService ss = new CalculatorService(wsdlURL, SERVICE_NAME);
        Calculator port = ss.getCalculatorPort();  
        
        {
        System.out.println("Invoking add...");
        int _add_a = -1559718132;
        int _add_b = 47813961;
        int _add__return = port.add(_add_a, _add_b);
        System.out.println("add.result=" + _add__return);


        }
        {
        System.out.println("Invoking subtract...");
        int _subtract_a = -1592702081;
        int _subtract_b = 466706718;
        int _subtract__return = port.subtract(_subtract_a, _subtract_b);
        System.out.println("subtract.result=" + _subtract__return);


        }

        System.exit(0);
    }

}
